-- Insertion des salles
INSERT INTO room(id, name) VALUES(1, 'A1');
INSERT INTO room(id, name) VALUES(2, 'A2');
INSERT INTO room(id, name) VALUES(3, 'A3');
INSERT INTO room(id, name) VALUES(4, 'A4');
INSERT INTO room(id, name) VALUES(5, 'A5');
INSERT INTO room(id, name) VALUES(6, 'A6');
INSERT INTO room(id, name) VALUES(7, 'A7');
INSERT INTO room(id, name) VALUES(8, 'A8');
INSERT INTO room(id, name) VALUES(9, 'A9');
INSERT INTO room(id, name) VALUES(10, 'B1');
INSERT INTO room(id, name) VALUES(11, 'B2');
INSERT INTO room(id, name) VALUES(12, 'B3');
INSERT INTO room(id, name) VALUES(13, 'C1');
INSERT INTO room(id, name) VALUES(14, 'C2');
INSERT INTO room(id, name) VALUES(15, 'C3');
INSERT INTO room(id, name) VALUES(16, 'C4');
INSERT INTO room(id, name) VALUES(17, 'C5');
INSERT INTO room(id, name) VALUES(18, 'C6');
INSERT INTO room(id, name) VALUES(19, 'C7');
INSERT INTO room(id, name) VALUES(20, 'C8');
INSERT INTO room(id, name) VALUES(21, 'D1');
INSERT INTO room(id, name) VALUES(22, 'D2');
INSERT INTO room(id, name) VALUES(23, 'D3');
INSERT INTO room(id, name) VALUES(24, 'D4');
INSERT INTO room(id, name) VALUES(25, 'E1');
INSERT INTO room(id, name) VALUES(26, 'E2');
INSERT INTO room(id, name) VALUES(27, 'E3');
INSERT INTO room(id, name) VALUES(28, 'E4');
INSERT INTO room(id, name) VALUES(29, 'E5');
INSERT INTO room(id, name) VALUES(30, 'E6');
INSERT INTO room(id, name) VALUES(31, 'F1');
INSERT INTO room(id, name) VALUES(32, 'G1');
INSERT INTO room(id, name) VALUES(33, 'G2');
INSERT INTO room(id, name) VALUES(34, 'G3');
INSERT INTO room(id, name) VALUES(35, 'G4');
INSERT INTO room(id, name) VALUES(36, 'G5');
INSERT INTO room(id, name) VALUES(37, 'G6');
INSERT INTO room(id, name) VALUES(38, 'G7');
INSERT INTO room(id, name) VALUES(39, 'H1');
INSERT INTO room(id, name) VALUES(40, 'H2');
INSERT INTO room(id, name) VALUES(41, 'H3');
INSERT INTO room(id, name) VALUES(42, 'J1');
INSERT INTO room(id, name) VALUES(43, 'J2');
INSERT INTO room(id, name) VALUES(44, 'J3');
INSERT INTO room(id, name) VALUES(45, 'J4');
INSERT INTO room(id, name) VALUES(46, 'J5');
INSERT INTO room(id, name) VALUES(47, 'J6');
INSERT INTO room(id, name) VALUES(48, 'J7');
INSERT INTO room(id, name) VALUES(49, 'K1');
INSERT INTO room(id, name) VALUES(50, 'L1');
INSERT INTO room(id, name) VALUES(51, 'M1');
INSERT INTO room(id, name) VALUES(52, 'M2');
INSERT INTO room(id, name) VALUES(53, 'M3');
INSERT INTO room(id, name) VALUES(54, 'O1');
INSERT INTO room(id, name) VALUES(55, 'P1');
INSERT INTO room(id, name) VALUES(56, 'R1');
INSERT INTO room(id, name) VALUES(57, 'S1');
INSERT INTO room(id, name) VALUES(58, 'S2');
INSERT INTO room(id, name) VALUES(59, 'S3');
INSERT INTO room(id, name) VALUES(60, 'T1');
INSERT INTO room(id, name) VALUES(61, 'T2');
INSERT INTO room(id, name) VALUES(62, 'T3');
INSERT INTO room(id, name) VALUES(63, 'T4');
INSERT INTO room(id, name) VALUES(64, 'T5');
INSERT INTO room(id, name) VALUES(65, 'T6');
INSERT INTO room(id, name) VALUES(66, 'T7');
INSERT INTO room(id, name) VALUES(67, 'T8');
INSERT INTO room(id, name) VALUES(68, 'T9');
INSERT INTO room(id, name) VALUES(69, 'U1');
INSERT INTO room(id, name) VALUES(70, 'U2');
INSERT INTO room(id, name) VALUES(71, 'U3');
INSERT INTO room(id, name) VALUES(72, 'V1');
INSERT INTO room(id, name) VALUES(73, 'V2');
INSERT INTO room(id, name) VALUES(74, 'V3');
INSERT INTO room(id, name) VALUES(75, 'V4');
INSERT INTO room(id, name) VALUES(76, 'V5');
INSERT INTO room(id, name) VALUES(77, 'V6');
INSERT INTO room(id, name) VALUES(78, 'V7');
INSERT INTO room(id, name) VALUES(79, 'V8');
INSERT INTO room(id, name) VALUES(80, 'V9');
INSERT INTO room(id, name) VALUES(81, 'W1');

-- Insertion des joueurs
INSERT INTO player(id, name, has_played, hidden, dead, current_room_id) VALUES(1, 'Tueur' , false, false, false, 1);
INSERT INTO player(id, name, has_played, hidden, dead, current_room_id) VALUES(2, 'Proie violette' , false, false, false, 2);
INSERT INTO player(id, name, has_played, hidden, dead, current_room_id) VALUES(3, 'Proie bleue' , false, false, false, 1);
INSERT INTO player(id, name, has_played, hidden, dead, current_room_id) VALUES(4, 'Proie verte' , false, false, false, 2);
INSERT INTO player(id, name, has_played, hidden, dead, current_room_id) VALUES(4, 'Proie rouge' , false, false, false, 2);
INSERT INTO player(id, name, has_played, hidden, dead, current_room_id) VALUES(4, 'Proie orange' , false, false, false, 2);
INSERT INTO player(id, name, has_played, hidden, dead, current_room_id) VALUES(4, 'Proie blanche' , false, false, false, 2);

-- Voisinage des salles
INSERT INTO neighbour_rooms(room1, room2) VALUES (1, 4);
INSERT INTO neighbour_rooms(room1, room2) VALUES (1, 42);
INSERT INTO neighbour_rooms(room1, room2) VALUES (1, 43);
INSERT INTO neighbour_rooms(room1, room2) VALUES (2, 3);
INSERT INTO neighbour_rooms(room1, room2) VALUES (2, 60);
INSERT INTO neighbour_rooms(room1, room2) VALUES (3, 4);
INSERT INTO neighbour_rooms(room1, room2) VALUES (3, 42);
INSERT INTO neighbour_rooms(room1, room2) VALUES (4, 5);
INSERT INTO neighbour_rooms(room1, room2) VALUES (4, 39);
INSERT INTO neighbour_rooms(room1, room2) VALUES (5, 6);
INSERT INTO neighbour_rooms(room1, room2) VALUES (5, 43);
INSERT INTO neighbour_rooms(room1, room2) VALUES (5, 45);
INSERT INTO neighbour_rooms(room1, room2) VALUES (6, 45);
INSERT INTO neighbour_rooms(room1, room2) VALUES (6, 35);
INSERT INTO neighbour_rooms(room1, room2) VALUES (7, 8);
INSERT INTO neighbour_rooms(room1, room2) VALUES (7, 55);
INSERT INTO neighbour_rooms(room1, room2) VALUES (8, 47);
INSERT INTO neighbour_rooms(room1, room2) VALUES (8, 32);
INSERT INTO neighbour_rooms(room1, room2) VALUES (9, 40);
INSERT INTO neighbour_rooms(room1, room2) VALUES (9, 54);
INSERT INTO neighbour_rooms(room1, room2) VALUES (9, 55);
INSERT INTO neighbour_rooms(room1, room2) VALUES (9, 48);
INSERT INTO neighbour_rooms(room1, room2) VALUES (10, 72);
INSERT INTO neighbour_rooms(room1, room2) VALUES (10, 73);
INSERT INTO neighbour_rooms(room1, room2) VALUES (11, 26);
INSERT INTO neighbour_rooms(room1, room2) VALUES (11, 40);
INSERT INTO neighbour_rooms(room1, room2) VALUES (11, 57);
INSERT INTO neighbour_rooms(room1, room2) VALUES (11, 60);
INSERT INTO neighbour_rooms(room1, room2) VALUES (11, 73);
INSERT INTO neighbour_rooms(room1, room2) VALUES (12, 78);
INSERT INTO neighbour_rooms(room1, room2) VALUES (13, 22);
INSERT INTO neighbour_rooms(room1, room2) VALUES (13, 61);
INSERT INTO neighbour_rooms(room1, room2) VALUES (13, 78);
INSERT INTO neighbour_rooms(room1, room2) VALUES (14, 62);
INSERT INTO neighbour_rooms(room1, room2) VALUES (14, 76);
INSERT INTO neighbour_rooms(room1, room2) VALUES (15, 23);
INSERT INTO neighbour_rooms(room1, room2) VALUES (15, 63);
INSERT INTO neighbour_rooms(room1, room2) VALUES (15, 79);
INSERT INTO neighbour_rooms(room1, room2) VALUES (16, 64);
INSERT INTO neighbour_rooms(room1, room2) VALUES (16, 76);
INSERT INTO neighbour_rooms(room1, room2) VALUES (17, 65);
INSERT INTO neighbour_rooms(room1, room2) VALUES (17, 76);
INSERT INTO neighbour_rooms(room1, room2) VALUES (18, 24);
INSERT INTO neighbour_rooms(room1, room2) VALUES (18, 28);
INSERT INTO neighbour_rooms(room1, room2) VALUES (18, 66);
INSERT INTO neighbour_rooms(room1, room2) VALUES (18, 79);
INSERT INTO neighbour_rooms(room1, room2) VALUES (19, 67);
INSERT INTO neighbour_rooms(room1, room2) VALUES (19, 80);
INSERT INTO neighbour_rooms(room1, room2) VALUES (20, 67);
INSERT INTO neighbour_rooms(room1, room2) VALUES (20, 80);
INSERT INTO neighbour_rooms(room1, room2) VALUES (21, 51);
INSERT INTO neighbour_rooms(room1, room2) VALUES (25, 26);
INSERT INTO neighbour_rooms(room1, room2) VALUES (25, 73);
INSERT INTO neighbour_rooms(room1, room2) VALUES (26, 73);
INSERT INTO neighbour_rooms(room1, room2) VALUES (27, 57);
INSERT INTO neighbour_rooms(room1, room2) VALUES (27, 72);
INSERT INTO neighbour_rooms(room1, room2) VALUES (29, 76);
INSERT INTO neighbour_rooms(room1, room2) VALUES (30, 76);
INSERT INTO neighbour_rooms(room1, room2) VALUES (31, 57);
INSERT INTO neighbour_rooms(room1, room2) VALUES (32, 58);
INSERT INTO neighbour_rooms(room1, room2) VALUES (33, 32);
INSERT INTO neighbour_rooms(room1, room2) VALUES (33, 34);
INSERT INTO neighbour_rooms(room1, room2) VALUES (34, 35);
INSERT INTO neighbour_rooms(room1, room2) VALUES (35, 37);
INSERT INTO neighbour_rooms(room1, room2) VALUES (36, 37);
INSERT INTO neighbour_rooms(room1, room2) VALUES (36, 76);
INSERT INTO neighbour_rooms(room1, room2) VALUES (37, 38);
INSERT INTO neighbour_rooms(room1, room2) VALUES (38, 80);
INSERT INTO neighbour_rooms(room1, room2) VALUES (39, 41);
INSERT INTO neighbour_rooms(room1, room2) VALUES (39, 72);
INSERT INTO neighbour_rooms(room1, room2) VALUES (39, 74);
INSERT INTO neighbour_rooms(room1, room2) VALUES (39, 75);
INSERT INTO neighbour_rooms(room1, room2) VALUES (40, 52);
INSERT INTO neighbour_rooms(room1, room2) VALUES (40, 74);
INSERT INTO neighbour_rooms(room1, room2) VALUES (41, 77);
INSERT INTO neighbour_rooms(room1, room2) VALUES (41, 78);
INSERT INTO neighbour_rooms(room1, room2) VALUES (41, 80);
INSERT INTO neighbour_rooms(room1, room2) VALUES (42, 50);
INSERT INTO neighbour_rooms(room1, room2) VALUES (43, 44);
INSERT INTO neighbour_rooms(room1, room2) VALUES (44, 45);
INSERT INTO neighbour_rooms(room1, room2) VALUES (46, 48);
INSERT INTO neighbour_rooms(room1, room2) VALUES (46, 54);
INSERT INTO neighbour_rooms(room1, room2) VALUES (47, 54);
INSERT INTO neighbour_rooms(room1, room2) VALUES (47, 55);
INSERT INTO neighbour_rooms(room1, room2) VALUES (49, 51);
INSERT INTO neighbour_rooms(room1, room2) VALUES (49, 52);
INSERT INTO neighbour_rooms(room1, room2) VALUES (49, 53);
INSERT INTO neighbour_rooms(room1, room2) VALUES (49, 69);
INSERT INTO neighbour_rooms(room1, room2) VALUES (51, 75);
INSERT INTO neighbour_rooms(room1, room2) VALUES (52, 55);
INSERT INTO neighbour_rooms(room1, room2) VALUES (53, 58);
INSERT INTO neighbour_rooms(room1, room2) VALUES (53, 59);
INSERT INTO neighbour_rooms(room1, room2) VALUES (53, 75);
INSERT INTO neighbour_rooms(room1, room2) VALUES (56, 69);
INSERT INTO neighbour_rooms(room1, room2) VALUES (57, 70);
INSERT INTO neighbour_rooms(room1, room2) VALUES (57, 72);
INSERT INTO neighbour_rooms(room1, room2) VALUES (57, 73);
INSERT INTO neighbour_rooms(room1, room2) VALUES (58, 59);
INSERT INTO neighbour_rooms(room1, room2) VALUES (60, 74);
INSERT INTO neighbour_rooms(room1, room2) VALUES (68, 80);
INSERT INTO neighbour_rooms(room1, room2) VALUES (69, 70);
INSERT INTO neighbour_rooms(room1, room2) VALUES (69, 71);
INSERT INTO neighbour_rooms(room1, room2) VALUES (69, 81);
INSERT INTO neighbour_rooms(room1, room2) VALUES (76, 77);
INSERT INTO neighbour_rooms(room1, room2) VALUES (77, 78);
INSERT INTO neighbour_rooms(room1, room2) VALUES (78, 79);
INSERT INTO neighbour_rooms(room1, room2) VALUES (79, 80);
